name: Download translations from Crowdin

on:
  schedule:
    # runs every 12 hours
    - cron: '0 */12 * * *'

permissions:
  pull-requests: write

jobs:
  crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Synchronize with Crowdin
        uses: crowdin/github-action@v1
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true

          base_path: 'pillarbox-web'
          source: 'src/lang/en.json'
          translation: 'src/lang/%locale%.%file_extension%'

          create_pull_request: true
          localization_branch_name: 'chore/i18n_crowdin_translations'
          commit_message: 'chore(i18n): new %language% translations'
          pull_request_base_branch_name: 'main'
          pull_request_title: 'New Crowdin translations'
          pull_request_body: 'Add %language% translations dowloaded from Crowdin'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
